# Generated by Django 2.2.5 on 2019-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20191009_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticker',
            fields=[
                ('company_name', models.TextField()),
                ('ticker_symbols', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
